#!/bin/bash
CURPATH=$(pwd)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 
#cd $DIR
classes=$DIR
classpath=$classes:$HOME/Desktop/zbin/G2_commons-collections4-4.4.jar:$HOME/Desktop/zbin/G2_zxing.jar:$HOME/Desktop/zbin/G2_gmssl_provider.jar:$HOME/Desktop/zbin/G2_activation-1.1.1.jar:$HOME/Desktop/zbin/G2_javaparser.jar:$HOME/Desktop/zbin/G2_mail-1.4.7.jar:$HOME/Desktop/zbin/G2_commons-compress-1.20.jar:$HOME/Desktop/zbin/G2_commons-exec-1.3.jar:$HOME/Desktop/zbin/G2_commons-io-2.6.jar:$HOME/Desktop/zbin/G2_commons-logging-api.jar:$HOME/Desktop/zbin/G2_commons-math3-3.6.1.jar:$HOME/Desktop/zbin/G2_dom4j-1.6.1.jar:$HOME/Desktop/zbin/G2_fastjson.jar:$HOME/Desktop/zbin/G2_fontbox.jar:$HOME/Desktop/zbin/G2_guava-25.0-jre.jar:$HOME/Desktop/zbin/G2_guava.jar:$HOME/Desktop/zbin/G2_hutool.jar:$HOME/Desktop/zbin/G2_isoparser-1.9.27.jar:$HOME/Desktop/zbin/G2_itext-asian-5.2.0.jar:$HOME/Desktop/zbin/G2_itextpdf-5.5.13.1.jar:$HOME/Desktop/zbin/G2_javax.xml.bind.jar:$HOME/Desktop/zbin/G2_jave.jar:$HOME/Desktop/zbin/G2_jshortcut_oberzalek.jar:$HOME/Desktop/zbin/G2_json-lib-2.1-.jar:$HOME/Desktop/zbin/G2_jsoup.jar:$HOME/Desktop/zbin/G2_metadata-extractor-2.11.0.jar:$HOME/Desktop/zbin/G2_mp3agic-0.9.1.jar:$HOME/Desktop/zbin/G2_okhttp-3.11.0.jar:$HOME/Desktop/zbin/G2_okio-1.14.0.jar:$HOME/Desktop/zbin/G2_org.apache.poi.xwpf.converter.pdf-1.0.6.jar:$HOME/Desktop/zbin/G2_pdfbox.jar:$HOME/Desktop/zbin/G2_pinyin4j.jar:$HOME/Desktop/zbin/G2_poi-5.0.0.jar:$HOME/Desktop/zbin/G2_poi-ooxml-5.0.0.jar:$HOME/Desktop/zbin/G2_poi-ooxml-schemas-4.1.2.jar:$HOME/Desktop/zbin/G2_poi-scratchpad-5.0.0.jar:$HOME/Desktop/zbin/G2_selenium-api-3.141.59.jar:$HOME/Desktop/zbin/G2_selenium-chrome-driver-3.141.59.jar:$HOME/Desktop/zbin/G2_selenium-remote-driver-3.141.59.jar:$HOME/Desktop/zbin/G2_SparseBitSet-1.2.jar:$HOME/Desktop/zbin/G2_spire.presentation.free-3.9.0.jar:$HOME/Desktop/zbin/G2_sunjce_provider.jar:$HOME/Desktop/zbin/G2_webp-imageio.jar:$HOME/Desktop/zbin/G2_xercesImpl.jar:$HOME/Desktop/zbin/G2_xmlbeans-4.0.0.jar:$HOME/Desktop/zbin/G2_xmpcore-5.1.2.jar:$HOME/Desktop/zbin/

javac -classpath $classpath -encoding UTF-8 $HOME/Desktop/zbin/G2_ApplyRuleFor_TypeFile.java
java  -classpath $classpath   -Xmx10240m -Xms10240m -Xmn5120m   -Dfile.encoding=UTF-8   G2_ApplyRuleFor_TypeFile  $1 $2 $3 $4 $5 $6 $7 $8 $9 
